name: "cron job"
on:
  schedule:
    - cron:  '5 * * * *'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: install npm
        run: npm install
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: install railway cli
        run: npm i -g @railway/cli
      - name: railway login
        run: railway login
      - name: railway project select
        run: railway link PROJECT_ID
      - name: run batch
        run: RAILWAY_TOKEN=TOKEN railway run bundle exec rails runner lib/batch/contributor_commit_collector.rb
