name: "manul cron job"

on: [ workflow_dispatch ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: bundle install
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install npm
        run: npm install
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: run batch
        run: railway run bundle exec rails runner lib/batch/contributor_commit_collector.rb
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
